all:
	g++ -g -Wall -std=c++11 -o webserver -I/usr/local/include/libbson-1.0 -I/usr/local/include/libmongoc-1.0 -L/usr/local/lib WebServer.cpp ConfigStore.cpp tinyxml2.cpp Database.cpp Email.cpp binn.cpp -pthread -lmongoc-1.0 -lbson-1.0 -lssl -lcrypto




